#set page(margin:(x: 1.5cm, y: 1.5cm), header: align(right)[])

#v(1cm)
#text(size: 2em)[Supermarket brand accused of using facial recognition for surge pricing]
#v(-4mm)
#text(size: 1.2em, weight: "bold")[_The Independent_, October 2024]

#set text(font: "EB Garamond", size: 1.1em)

#v(1cm)

Michigan congresswoman Rashida Tlaib has called on Kroger, one of the biggest supermarket chains in the US, to answer questions about its use of electronic shelving labels and facial recognition technology.

The Democrat told CEO Rodney McMullen she was worried about that technology being used discriminately, and was concerned about the potential it could lead to prices rising for essential goods — something that one of America's largest supermarket chains has denied would happen. [...]

Tlaib said it was her understanding that, through a partnership with Microsoft, Kroger was intending to place cameras at its digital displays, using facial recognition to determine the gender and age of the store's customers who are captured on camera, and using that information to present them with targeted advertising on the electronic shelving labels.

"Studies have shown that facial recognition technology is flawed and can lead to discrimination in predominantly Black and brown communities," Tlaib said. "The racial biases of facial recognition technology are well-documented and should not be extended into our grocery stores." She said this was concerning given complaints about the rising cost of groceries at big retailers across the country, and that Kroger's electronic tools could be "abused in the pursuit of profit." [...]

But Kroger claimed that its business model was "built on a foundation of lowering prices to attract more customers. To be clear, Kroger does not and has never engaged in 'surge pricing.' Any test of electronic shelf tags is designed to lower prices for more customers where it matters most. To suggest otherwise is not true," the grocer said. [...] They said the company has never used facial recognition in stores, and are not aware of any future plans to do so.

Kroger did not respond to The Independent's multiple requests for comment, but a Microsoft spokesperson also denied the use of facial recognition technology. "Kroger is not using Microsoft facial recognition technology, and the current digital price tag technology being used is not the technology we piloted in 2019," they said.

In 2019, Fast Company reported that Kroger was piloting a program called Enhanced Display for Grocery Environment (EDGE), and that it would implement artificial intelligence-powered facial recognition technology in some of its displays. An announcement from Microsoft published at around the same time does not mention facial recognition. [...]

Microsoft posted an article in June 2018 detailing Kroger EDGE, which it presented as more "environmentally efficient" than paper tags. "EDGE — which stands for Enhanced Display for Grocery Environment — relies on Microsoft Azure to store and process volumes of data generated by customer actions on and around the shelves," Microsoft said.

#pagebreak()

== Questions

1. The article says Kroger claims its digital price tags help lower prices. Explain how Kroger denied that it charges people different prices at different times (called "surge pricing")?

2. Back in 2019, a magazine reported that Kroger was testing face-scanning cameras in some stores. But now, a Microsoft spokesperson says that's not the technology being used today. Why does this make it hard to know if Kroger is telling the full truth about not using face recognition now?

3. Tlaib is worried this technology could be used to raise prices, while Kroger says it's only meant to lower them. Since the same electronic price tags could be used either way, what would decide which one actually happens? Why might a company's promise not be enough to guarantee that prices will only go down and never go up?

4. Facial recognition technology has documented racial biases, yet it's increasingly being tested in everyday commercial spaces like grocery stores — places people cannot easily avoid if they need to buy food. What does it mean for a technology with known discriminatory effects to be deployed in essential, non-optional public spaces, and what does this reveal about the tension between corporate surveillance for profit and individual freedom from being tracked, categorized, and profiled without consent?